config/routes.rb
Rails.application.routes.draw do
  get 'redirectpage/statuspayment'
  resources :payments
  get 'pages/home'
  get 'pages/about'
  draw :admin
  # root :to => "pages#home"
  
  resources :stuffs do
    resources :payments
  end

  resources :redirectpage do
    collection do
      post :statuspayment
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/stuff.rb
class Stuff < ApplicationRecord
    belongs_to :admin, optional: true
    has_many :payments
end

app/controllers/admins/stuffs_controller.rb
class Admins::StuffsController < ApplicationController
  before_action :set_stuff, only: %i[ show edit update destroy ]

  # GET /stuffs or /stuffs.json
  def index
    @stuffs = Stuff.all
  end

  # GET /stuffs/1 or /stuffs/1.json
  def show
  end

  # GET /stuffs/new
  def new
    @stuff = current_admin.stuffs.new
  end

  # GET /stuffs/1/edit
  def edit
  end

  # POST /stuffs or /stuffs.json
  def create
    @stuff = current_admin.stuffs.new(stuff_params)

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to admin_stuff_url(@stuff), notice: "Stuff was successfully created." }
        format.json { render :show, status: :created, location: @stuff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuffs/1 or /stuffs/1.json
  def update
    respond_to do |format|
      if @stuff.update(stuff_params)
        format.html { redirect_to admin_stuff_url(@stuff), notice: "Stuff was successfully updated." }
        format.json { render :show, status: :ok, location: @stuff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1 or /stuffs/1.json
  def destroy
    @stuff.destroy

    respond_to do |format|
      format.html { redirect_to admin_stuffs_url, notice: "Stuff was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuff
      @stuff = current_admin.stuffs.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stuff_params
      params.require(:stuff).permit(:stuff_name, :stuff_price, :stuff_code)
    end
end

app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  before_action :set_stuff, only: %i[ show edit update destroy ]

  # GET /stuffs or /stuffs.json
  def index
    @stuffs = Stuff.all
  end

  # GET /stuffs/1 or /stuffs/1.json
  def show
  end

  # GET /stuffs/new
  def new
    @stuff = Stuff.new
  end

  # GET /stuffs/1/edit
  def edit
  end

  # POST /stuffs or /stuffs.json
  def create
    @stuff = Stuff.new(stuff_params)

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to stuff_url(@stuff), notice: "Stuff was successfully created." }
        format.json { render :show, status: :created, location: @stuff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuffs/1 or /stuffs/1.json
  def update
    respond_to do |format|
      if @stuff.update(stuff_params)
        format.html { redirect_to stuff_url(@stuff), notice: "Stuff was successfully updated." }
        format.json { render :show, status: :ok, location: @stuff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1 or /stuffs/1.json
  def destroy
    @stuff.destroy

    respond_to do |format|
      format.html { redirect_to stuffs_url, notice: "Stuff was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuff
      @stuff = Stuff.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stuff_params
      params.require(:stuff).permit(:stuff_name, :stuff_price, :stuff_code)
    end
end

app/helpers/stuffs_helper.rb
module StuffsHelper
end

app/views/stuffs/_form.html.erb
<%= form_with(model: stuff, class: "contents") do |form| %>
  <% if stuff.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(stuff.errors.count, "error") %> prohibited this stuff from being saved:</h2>

      <ul>
        <% stuff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :stuff_name %>
    <%= form.text_field :stuff_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stuff_price %>
    <%= form.text_field :stuff_price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stuff_code %>
    <%= form.text_field :stuff_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/stuffs/_stuff.html.erb
<div id="<%= dom_id stuff %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Stuff name:</strong>
    <%= stuff.stuff_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Stuff price:</strong>
    <%= stuff.stuff_price %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Stuff code:</strong>
    <%= stuff.stuff_code %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this stuff", stuff, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Buy it Now", new_stuff_payment_path(stuff.id), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/stuffs/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Stuffs</h1>
    
  </div>

  <div id="stuffs" class="min-w-full">
    <%= render @stuffs %>
  </div>
</div>