config/routes.rb
Rails.application.routes.draw do
  get 'redirectpage/statuspayment'
  resources :payments
  get 'pages/home'
  get 'pages/about'
  draw :admin
  # root :to => "pages#home"
  
  resources :stuffs do
    resources :payments
  end

  resources :redirectpage do
    collection do
      post :statuspayment
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :stuff

    def generate_checksum
 
    
        data = "#{payer_email}|#{payer_name}|#{payer_phone}|#{""}|#{stuff.stuff_code}|#{stuff.stuff_name}|http://127.0.0.1:3010/redirectpage/statuspayment|#{stuff.stuff_price}|#{"e7c5d7eb-3707-4a0b-9f79-5f015941adf7"}"
        puts(data)
        checksum_token = "6d6a89340596f76a0b2ab67bdac31e27d36a30861be194b37d564a6f07c86633"
        OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), checksum_token, data)
    
    end    
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :get_stuff
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = @stuff.payments
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = @stuff.payments.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    if @payment.save
      Rails.logger.debug("loading checksum #{@payment.generate_checksum}")
      
      params_api = {
        uid: "e7c5d7eb-3707-4a0b-9f79-5f015941adf7",
        checksum: @payment.generate_checksum,
        buyer_email: @payment.payer_email,
        buyer_name: @payment.payer_name,
        buyer_phone: @payment.payer_phone,
        order_number: @stuff.stuff_code,
        product_description: @stuff.stuff_name,
        transaction_amount: @stuff.stuff_price,
        callback_url: "",
        redirect_url: "http://127.0.0.1:3010/redirectpage/statuspayment",
        token: "osjbg2SM9p1q4v-PyYqb",
        redirect_post: "true"
        
       }

      redirect_post('https://sandbox.securepay.my/api/v1/payments',            # URL, looks understandable
        params: params_api)                
      end

  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def get_stuff
      @stuff = Stuff.find(params[:stuff_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = @stuff.payments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:payer_email, :payer_name, :payer_address, :payer_phone, :stuff_id)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= simple_form_for [@stuff, @payment], data:{turbo:false} do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :payer_email %>
    <%= form.text_field :payer_email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :payer_name %>
    <%= form.text_field :payer_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :payer_address %>
    <%= form.text_field :payer_address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :payer_phone %>
    <%= form.text_field :payer_phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5" style="display: none;">
    <%= form.label :stuff_id %>
    <%= form.number_field :stuff_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Payer email:</strong>
    <%= payment.payer_email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Payer name:</strong>
    <%= payment.payer_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Payer address:</strong>
    <%= payment.payer_address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Payer phone:</strong>
    <%= payment.payer_phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Stuff:</strong>
    <%= payment.stuff_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this payment", payment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this payment', edit_payment_path(payment), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/payments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing payment</h1>

  <%= render "form", payment: @payment %>

  <%= link_to "Show this payment", @payment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to payments", payments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/payments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Payments</h1>
    <%= link_to 'New payment', new_payment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="payments" class="min-w-full">
    <%= render @payments %>
  </div>
</div>

app/views/payments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New payment</h1>

  <%= render "form", payment: @payment %>

  <%= link_to 'Back to stuff', stuffs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/payments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @payment %>

    <%= link_to 'Edit this payment', edit_payment_path(@payment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this payment', payment_path(@payment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to payments', payments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>